### ISSUE TITLE
SyntaxError: Unexpected strict mode reserved word

### ISSUE THREAD

**Issue by leighghunt** [kristianmandrup/generator-aurelia-ts#11]
I get the following whilst running yo:

```
/Users/lhunt/.npm-packages/lib/node_modules/generator-aurelia-ts/generators/styles/index.js:24
let log = info;
^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.defineProperty.get [as aurelia-ts:styles] (/Users/lhunt/.npm-packages/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:40:23)
    at Store.get (/Users/lhunt/.npm-packages/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:64:35)
    at Environment.get (/Users/lhunt/.npm-packages/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:227:21)
```

On Windows, the yeoman process then bails. On Mac, it carries on and finished building the scaffolding code.

The line in question seems to have been introduced in https://github.com/kristianmandrup/generator-aurelia-ts/commit/af6ad165321c727255f81037ffc4b20bc0ebb73d#diff-1bf8f3a86bd849b9903ec499bf556b12R21 and removed in https://github.com/kristianmandrup/generator-aurelia-ts/commit/ca56d037ed511cad49547a5f8328097f4e009d96#diff-1bf8f3a86bd849b9903ec499bf556b12L24.

Can I ignore the error message?

yo output:

```
dev % yo
? 'Allo Leigh! What would you like to do? Aurelia Ts

Make sure you are in the directory you want to scaffold into.
This generator can also be run with: yo aurelia-ts

? application (module) name: test
? application title: test
? github account: leighghunt
? Your email: ###########
? Your name: Leigh Hunt
? Install Styles: Yes
? Install Aurelia CLI: Yes
? Support IE9: Yes
? Visual Studio: No
? Install Aurelia Plugins: No
? Install TypeScript: No
? Install UI Frameworks: Yes
   create styles
    force test
   create /Users/lhunt/dev/test/e2e/dist/demo.spec.js
   create /Users/lhunt/dev/test/e2e/dist/skeleton.po.js
   create /Users/lhunt/dev/test/e2e/dist/welcome.po.js
   create /Users/lhunt/dev/test/e2e/src/demo.spec.js
   create /Users/lhunt/dev/test/e2e/src/skeleton.po.js
   create /Users/lhunt/dev/test/e2e/src/welcome.po.js
   create /Users/lhunt/dev/test/unit/app.spec.js
   create doc
   create /Users/lhunt/dev/doc/api.json
   create /Users/lhunt/dev/doc/CHANGELOG.md
   create src
   create build
   create /Users/lhunt/dev/build/args.js
   create /Users/lhunt/dev/build/babel-options.js
   create /Users/lhunt/dev/build/paths.js
   create /Users/lhunt/dev/build/tasks/build.js
   create /Users/lhunt/dev/build/tasks/clean.js
   create /Users/lhunt/dev/build/tasks/dev.js
   create /Users/lhunt/dev/build/tasks/doc.js
   create /Users/lhunt/dev/build/tasks/e2e.js
   create /Users/lhunt/dev/build/tasks/lint.js
   create /Users/lhunt/dev/build/tasks/prepare-release.js
   create /Users/lhunt/dev/build/tasks/serve.js
   create /Users/lhunt/dev/build/tasks/test.js
   create /Users/lhunt/dev/build/tasks/watch.js
   create package.json
   create index.html
   create aureliafile.js
   create src/app.js
   create .gitignore
   create README.md
    force .editorconfig
   create .jshintrc
    force .npmignore
   create aurelia.protractor.js
   create gulpfile.js
   create favicon.ico
   create config.js
   create jsconfig.json
   create karma.conf.js
   create protractor.conf.js
   create LICENSE

     _-----_
    |       |    .----------------------.
    |--(o)--|    |     Bye from us!     |
   `---------´   |      Chat soon.      |
    ( _´U`_ )    |                      |
    /___A___\    |      Yeoman team     |
     |  ~  |     |   http://yeoman.io   |
   __'.___.'__   '----------------------'
 ´   `  |° ´ Y ` 

/Users/lhunt/.npm-packages/lib/node_modules/generator-aurelia-ts/generators/styles/index.js:24
let log = info;
^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.defineProperty.get [as aurelia-ts:styles] (/Users/lhunt/.npm-packages/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:40:23)
    at Store.get (/Users/lhunt/.npm-packages/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:64:35)
    at Environment.get (/Users/lhunt/.npm-packages/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:227:21)
dev % 
warn Running jspm globally, it is advisable to locally install jspm via npm install jspm --save-dev.
     Looking up github:polymer/mutationobservers
     Updating registry cache...
ok   Installed polymer/mutationobservers as github:polymer/mutationobservers@^0.4.2 (0.4.2)
ok   Install tree has no forks.
     Looking up loader files...
       system.src.js
       system.js.map
       system.js
       system-polyfills.js
       system-csp-production.src.js
       system-polyfills.src.js
       system-csp-production.js
       system-polyfills.js.map
       system-csp-production.js.map

     Using loader versions:
       systemjs@0.18.9
     Looking up npm:babel-core
     Looking up npm:babel-runtime
     Looking up npm:core-js

warn Using local override for npm:core-js@0.9.18
ok   Installed babel as npm:babel-core@^5.1.13 (5.8.22)
     Looking up github:jspm/nodelibs-process
     Looking up github:systemjs/plugin-json
     Looking up github:jspm/nodelibs-fs
ok   Installed github:jspm/nodelibs-process@^0.1.0 (0.1.1)
     Looking up npm:process
ok   Installed github:systemjs/plugin-json@^0.1.0 (0.1.0)
ok   Installed github:jspm/nodelibs-fs@^0.1.0 (0.1.2)
ok   Installed npm:process@^0.10.0 (0.10.1)
ok   Installed babel-runtime as npm:babel-runtime@^5.1.13 (5.8.20)
ok   Installed core-js as npm:core-js@^0.9.4 (0.9.18)
ok   Loader files downloaded successfully

ok   Install complete.

```

**Comment by kristianmandrup** [comment]
The generator has been written in `strict mode` syntax, ie. with some new/modern ES2015 constructs such as `let`. The error is due to your node version being incompatible (old school). 
I should note this in the `readme`. Try the latest node 0.12.7 (untested) or even better, `iojs` 3.0 (the one I use), install globally via `nvm` and try again ;) Cheers!

PS: We are working on tests this week to make sure we have a good test suite...

**Comment by delebash** [comment]
I am running node version 12.7 on Windows 7 x64 and still get this error. I was trying to test to see about fixing issue https://github.com/kristianmandrup/generator-aurelia-ts/issues/7.  But got the above error.  I really do not want to switch to iojs, I have had problems in the past with node-gyp on windows, haven't tested lately.  Regarding the aurelia ts issue if you run jspm in your generator you automatically get the ts files so you should not have to do anything except reference them in your build task.  I can send you my gulp task, not sure about Visual Studio

**Comment by kristianmandrup** [comment]
Try the latest version `0.6.3` just published. I will test node 0.12.7 locally now to make sure.

**Comment by kristianmandrup** [comment]
ah yes, I get the same error :( Will drop `let` for now then...
Give me one hour ;)

**Comment by kristianmandrup** [comment]
Now tested all generators with node 0.12.x :)

**Comment by delebash** [comment]
It's always the little things, think something didn't get pushed to npm, just tried 0.7.0 and

module.js:338
    throw err;
          ^
Error: Cannot find module '../../lib'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (F:\Program Files\nodejs\global_npm\npm\node_modules\generator-aurelia-ts\generators\app\index.js:12:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by kristianmandrup** [comment]
Works fine on my machine using `npm link`. Just published `0.7.1`, maybe it fixes this?
Otherwise would love if you could clone, `npm link` and run it locally to see what could be the problem.
Thanks :)
So close....

**Comment by delebash** [comment]
npm link may be causing the problem if you have something linked locally but are not pushing to npm.  I will have to read up on npm link, I am not really that familiar but don't have the time right now.  As soon as I can I will take a look at it, but I think if you disable npm link you will probably see the issue.

**Comment by kristianmandrup** [comment]
Trying npm global install now. Thanks :)

**Comment by kristianmandrup** [comment]
It turned out it was due to a `package.json` setting `files:` which pointed to generators as the place with all the files. My collaborator Guillermo had added this "optimisation" without my knowledge...
However since `/lib` is outside the `/generators` folder so as not to be picked up as a generator, it was inaccessible. Tested and works now, both via `npm link` and global install. Finally :)

**Comment by delebash** [comment]
This issue is fixed, thanks!

But now it is not downloading aurelia via jspm, sometimes depending on the options it is not even running jspm.  Seems like the question decorate determines if it will run jspm but even choosing yes for decorate then choosing no for all other options it does not run jspm and install aurelia, not sure why, maybe I am not choosing the right options, but if I get the time I will investigate and either log further bugs or do a PR.

**Comment by telekosmos** [comment]
Well, definitely what you are talking about needs more testing. I'm getting back after some rest and will enhance the tests. 
Regarding to the `package.json` issue, it wasn't my intention optimize the generator but I found some issue during testing and had to change couple of very minor things which didn't work ☺️

**Comment by leighghunt** [comment]
Awesome - works now, thanks :-)
