### ISSUE TITLE
Error> events.js:141throw er; // Unhandled 'error' event on "yo aurelia-ts"

### ISSUE THREAD

**Issue by Geraldf** [kristianmandrup/generator-aurelia-ts#12]
Hi, after upgrading to iojs-v3.0.0 I receive the below error when running yo aurelia-ts.
any ideas how to solve this?
Gerald

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn jspm ENOENT
    at exports._errnoException (util.js:812:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)

**Comment by kristianmandrup** [comment]
Please try cloning the repo, then `npm link` and see how it goes. I will test it now using `npm install -g` on node 0.12 and iojs +2.0. Thanks ;)

**Comment by kristianmandrup** [comment]
Worked for me using iojs 2.3.4

``` sh
22:10 $ yo aurelia-ts
? application (package) name: sdgds
? title: dgdsg
? description: dgdgs
? github account: dsgds
? Your name: sdg
? Your email: sdg
? Support IE9: No
? Decorate the app? No
Writing app files...
copying /build -> /build
copying /doc -> /docs
copying /test -> /test
   create package.json
   create README.md
   create .gitignore
   create index.html
   create aureliafile.js
   create .editorconfig
   create .jshintrc
   create npmignore
   create aurelia.protractor.js
   create gulpfile.js
   create favicon.ico
   create config.js
   create jsconfig.json
   create karma.conf.js
   create protractor.conf.js
   create LICENSE
✔ ~/repos/test123/aurel 
22:10 $ node -v
v2.3.4
✔ ~/repos/test12
```

**Comment by Geraldf** [comment]
I still get the same error>
what I did:
nvm install iojs-v2.3.4
npm install -g yo bower grunt-cli gulp
npm install -g generator-aurelia-ts
yo aurelia-ts
? application (package) name: Main
? title: main
? description: 
? github account: gerald@fuchsclan.de
? Your name: Gerald
? Your email: gerald@fuchsclan.de
? Support IE9: Yes
? Decorate the app? Yes
Writing app files...
copying /build -> /build
copying /doc -> /docs
copying /test -> /test
   create package.json
   create README.md
   create .gitignore
   create index.html
   create aureliafile.js
   create .editorconfig
   create .jshintrc
   create npmignore
   create aurelia.protractor.js
   create gulpfile.js
   create favicon.ico
   create config.js
   create jsconfig.json
   create karma.conf.js
   create protractor.conf.js
   create LICENSE
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: spawn jspm ENOENT
    at exports._errnoException (util.js:814:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:430:9)
    at process._tickCallback (node.js:344:17)

**Comment by kristianmandrup** [comment]
OK, I will try to duplicate. Thanks :)

**Comment by kristianmandrup** [comment]
Error: spawn jspm ENOENT. Looks like it is not able to spawn the process to do `jspm install`.
Have you installed jspm on your system?

PS: ? github account: gerald@fuchsclan.de
Should NOT be an email but your github (or whichever git repo) username

Works for me:

``` sh
22:48 $ node -v
v3.0.0
✔ ~/repos/test123/aurel 
22:48 $ yo aurelia-ts
? application (package) name: main
? title: Main
? description: none
? github account: gerald@fuchsclan.de
? Your name: Gerald
? Your email: gerald@fuchsclan.de
? Support IE9: Yes
? Decorate the app? Yes
Writing app files...
copying /build -> /build
copying /doc -> /docs
copying /test -> /test
   create package.json
   create README.md
identical .gitignore
   create index.html
   create aureliafile.js
identical .editorconfig
identical .jshintrc
   create npmignore
   create aurelia.protractor.js
   create gulpfile.js
   create favicon.ico
   create config.js
   create jsconfig.json
   create karma.conf.js
   create protractor.conf.js
   create LICENSE
? Install Styles: (Y/n)      Looking up github:polymer/mutationobservers
     Updating registry cache...
ok   Installed polymer/mutationobservers as github:polymer/mutationobservers@^0.4.2 (0.4.2)
ok   Install tree has no forks.
     Looking up loader files...
       es6-module-loader.js
       es6-module-loader.js.map
       es6-module-loader.src.js
       system.js
       system.src.js
       system.js.map

     Using loader versions:
       es6-module-loader@0.16.6
       systemjs@0.16.11
     Looking up npm:babel-core
     Looking up npm:babel-runtime
     Looking up npm:core-js

warn Using local override for npm:core-js@0.9.18
     Looking up github:jspm/nodelibs-process
ok   Installed babel as npm:babel-core@^5.8.20 (5.8.22)
     Looking up github:jspm/nodelibs-fs
     Looking up github:systemjs/plugin-json
ok   Installed github:jspm/nodelibs-process@^0.1.0 (0.1.1)
     Looking up npm:process
ok   Installed npm:process@^0.10.0 (0.10.1)
ok   Installed babel-runtime as npm:babel-runtime@^5.8.20 (5.8.20)
ok   Installed github:systemjs/plugin-json@^0.1.0 (0.1.0)
ok   Installed github:jspm/nodelibs-fs@^0.1.0 (0.1.2)
ok   Installed core-js as npm:core-js@^0.9.4 (0.9.18)
ok   Loader files downloaded successfully

ok   Install complete.
```

**Comment by kristianmandrup** [comment]
Please follow this guide:

https://github.com/jspm/jspm-cli/wiki/Getting-Started

**Comment by Geraldf** [comment]
Hi Kristian, 
the jspm did the trick. thanks. Now it works. 
Gerald
