### ISSUE TITLE
When i tried to create entity in project folder , getting the following error)

### ISSUE THREAD

**Issue by AmsaveniMidhun** [kristianmandrup/generator-aurelia-ts#20]
E:\iloads-old>yo jhipster:entity truckowner

events.js:163
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'endsWith' of undefined
    at constructor.getAngularAppName (C:\Users\Wdsi\AppData\Roaming\npm\node_modules\generator-jhipster\generators\generator-base.js:1520:65)
    at constructor.getConfig (C:\Users\Wdsi\AppData\Roaming\npm\node_modules\generator-jhipster\generators\entity\index.js:142:40)
    at Object.<anonymous> (C:\Users\Wdsi\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:417:23)
    at C:\Users\Wdsi\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\node_modules\run-async\index.js:25:25
    at C:\Users\Wdsi\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\node_modules\run-async\index.js:24:19
    at C:\Users\Wdsi\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:418:9
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)

**Comment by kristianmandrup** [comment]
Yeah, sorry. I never completed this generator. But should give you a running start...
I was trying to help a jHipster friend escape from Angular 1 hell. I don't know much about jHipster, so maybe you will have more luck!

**Comment by AmsaveniMidhun** [comment]
My bad :(  Now i am getting this error, when i try to create entity.  

Though the generator is already been created !



E:\iloads-old>yo jhipster: entity TruckOwner
Error jhipster: entity TruckOwner

You don’t seem to have a generator with the name “jhipster:” installed.
But help is on the way:

You can see available generators via npm search yeoman-generator or via http://yeoman.io/generators/.
Install them with npm install generator-jhipster:.

To see all your installed generators run yo without any arguments. Adding the --help option will also show subgenerators.

If yo cannot find the generator, run yo doctor to troubleshoot your system.

**Comment by kristianmandrup** [comment]
Please fork the repo and work from there. Must of the grunt work has been done. There might be a few bugs, but mostly what is missing is the Aurelia REST endpoint integration with the jHipster backend... Would be so awesome to get it done! Have fun!

**Comment by kristianmandrup** [comment]
Ah, but this is a generator for TypeScript with Aurelia. There is another 80% done generator for Aurelia with jHipster. I got a bit confused.

https://github.com/kristianmandrup/aurelia-breeze-hipster-entity-generator
https://github.com/kristianmandrup/jhipster-aurelia-boilerplate

Good luck ;)
