### ISSUE TITLE
It keeps asking to install at the parent folder

### ISSUE THREAD

**Issue by vcardins** [kristianmandrup/generator-aurelia-ts#4]
Hi, even running the yo command from within a sub-folder, it always tries to install in the parent folder (from where I installed the generator globally) - http://screencast.com/t/GR3vFHgDx
Am I doing something wrong?

**Comment by leighghunt** [comment]
I had this too - clear up any unintended `.yo-rc.json` files - I think I created one unintentionally during a previous yo command.

```
Just found a `.yo-rc.json` in a parent directory.
Setting the project root at: .....
```

**Comment by kristianmandrup** [comment]
Thanks guys :) We need some more usage in the wild to update our docs with troubleshooting tips...

**Comment by kristianmandrup** [comment]
Updated docs with troubleshooting tip for this. Remove `.yo-rc.json` in any parent directory ;)
