### ISSUE TITLE
Aurelia now includes generated d.ts files

### ISSUE THREAD

**Issue by delebash** [kristianmandrup/generator-aurelia-ts#7]
Just letting you know that as of recent Aurelia now provides d.ts files with the framework.  There is a blog post on Aurelia's site describing this new feature of generating the d.ts files, although it is still a work in progress and may have some bugs. 

Nice job, thanks!

**Comment by kristianmandrup** [comment]
Thanks @delebash  ;) I've seen the blog post a while back but looked too complicated... would love for you to recommend some way to integrate TS support better with this generator.

**Comment by delebash** [comment]
Here is my gulp task just look at the typescript section, the paths are defined in the path.js file that you already have paths.sourceTS, paths.typings], {base: paths.root} also this statement typescript: require('typescript') is not required if you use gulp-typescript because gulp-typescript includes its own version, but it sometimes is outdated so if you install your own version of typescript then include the above statement, that way you can run with any typescript version you install ie 1.4, 1.5 beta...

https://gist.github.com/delebash/3654f6c747f529b9d029

**Comment by kristianmandrup** [comment]
Could you make a PR for these suggestions/fixes ;)
Latest release 0.7 is now Node 0.12 compatible on my system. Please test it out. Thanks :)

**Comment by delebash** [comment]
Sure, I just forked and was planning on doing a PR, still have an issue with 7.0 https://github.com/kristianmandrup/generator-aurelia-ts/issues/11.
